export interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  inStock: boolean;
  description: string;
  rating: number;
  brand: string;
  createdAt: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Laptop Pro X1",
    price: 1299,
    category: "Electronics",
    inStock: true,
    description: "High-performance laptop with 16GB RAM and 512GB SSD",
    rating: 4.5,
    brand: "TechPro",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Wireless Mouse M1",
    price: 49,
    category: "Accessories",
    inStock: true,
    description: "Ergonomic wireless mouse with long battery life",
    rating: 4.2,
    brand: "PeripheralTech",
    createdAt: "2024-01-16",
  },
  {
    id: 3,
    name: "4K Monitor Ultra",
    price: 599,
    category: "Electronics",
    inStock: false,
    description: "32-inch 4K monitor with HDR support",
    rating: 4.8,
    brand: "ViewTech",
    createdAt: "2024-01-17",
  },
  {
    id: 4,
    name: "Mechanical Keyboard K1",
    price: 159,
    category: "Accessories",
    inStock: true,
    description: "Mechanical keyboard with RGB backlight",
    rating: 4.6,
    brand: "PeripheralTech",
    createdAt: "2024-01-18",
  },
  {
    id: 5,
    name: "Gaming Headset Pro",
    price: 129,
    category: "Accessories",
    inStock: true,
    description: "7.1 surround sound gaming headset",
    rating: 4.3,
    brand: "AudioTech",
    createdAt: "2024-01-19",
  },
  {
    id: 6,
    name: "Tablet Air",
    price: 449,
    category: "Electronics",
    inStock: true,
    description: "10-inch tablet with retina display",
    rating: 4.7,
    brand: "TechPro",
    createdAt: "2024-01-20",
  },
  {
    id: 7,
    name: "Webcam HD",
    price: 79,
    category: "Accessories",
    inStock: false,
    description: "1080p HD webcam with built-in microphone",
    rating: 4.1,
    brand: "ViewTech",
    createdAt: "2024-01-21",
  },
  {
    id: 8,
    name: "External SSD 1TB",
    price: 199,
    category: "Storage",
    inStock: true,
    description: "Portable SSD with USB-C connection",
    rating: 4.9,
    brand: "StoragePro",
    createdAt: "2024-01-22",
  },
  {
    id: 9,
    name: "Graphics Card RTX",
    price: 799,
    category: "Components",
    inStock: false,
    description: "High-end graphics card for gaming",
    rating: 4.8,
    brand: "TechPro",
    createdAt: "2024-01-23",
  },
  {
    id: 10,
    name: "USB-C Hub",
    price: 69,
    category: "Accessories",
    inStock: true,
    description: "7-in-1 USB-C hub with HDMI",
    rating: 4.4,
    brand: "ConnectTech",
    createdAt: "2024-01-24",
  },
  {
    id: 11,
    name: "Wireless Earbuds",
    price: 159,
    category: "Audio",
    inStock: true,
    description: "True wireless earbuds with ANC",
    rating: 4.6,
    brand: "AudioTech",
    createdAt: "2024-01-25",
  },
  {
    id: 12,
    name: "Smart Watch X",
    price: 299,
    category: "Wearables",
    inStock: true,
    description: "Smart watch with health tracking",
    rating: 4.5,
    brand: "TechPro",
    createdAt: "2024-01-26",
  },
];